# database_queries.py

import psycopg2

def connect():
    try:
        # Connect to PostgreSQL
        conn = psycopg2.connect(
            database="ecommerce_system",  # Replace with your database name
            user="postgres",
            password="yourpassword",  # Replace with your PostgreSQL password
            host="127.0.0.1",
            port="5432"
        )
        print("Connection successful")
        return conn
    except Exception as e:
        print(f"Error connecting to database: {e}")

def execute_query(query):
    connection = connect()
    cursor = connection.cursor()
    cursor.execute(query)
    result = cursor.fetchall()
    cursor.close()
    connection.close()
    return result

# SQL Queries
if __name__ == "__main__":
    # Query 1: Retrieve top 5 customers who have purchased the most books
    query_1 = """
        SELECT C.customer_id, C.name, SUM(OD.quantity) AS total_books
        FROM Customers C
        JOIN Orders O ON C.customer_id = O.customer_id
        JOIN OrderDetails OD ON O.order_id = OD.order_id
        WHERE O.order_date > CURRENT_DATE - INTERVAL '1 year'
        GROUP BY C.customer_id
        ORDER BY total_books DESC
        LIMIT 5;
    """

    # Query 2: Calculate total revenue generated by each author
    query_2 = """
        SELECT B.author, SUM(OD.quantity * B.price) AS total_revenue
        FROM Books B
        JOIN OrderDetails OD ON B.book_id = OD.book_id
        GROUP BY B.author;
    """

    # Query 3: Retrieve all books ordered more than 10 times
    query_3 = """
        SELECT B.title, SUM(OD.quantity) AS total_quantity
        FROM Books B
        JOIN OrderDetails OD ON B.book_id = OD.book_id
        GROUP BY B.book_id
        HAVING SUM(OD.quantity) > 10;
    """

    # Execute queries
    print("Top 5 customers who purchased the most books:", execute_query(query_1))
    print("Total revenue by each author:", execute_query(query_2))
    print("Books ordered more than 10 times:", execute_query(query_3))
